#!/usr/bin/env node
/**
 * Renders public/og.png — the 1200x630 card every share of this site unfurls as.
 *
 * Deliberately not part of `npm run build`. It needs a Chrome, which the
 * Cloudflare build image should not have to provide, and the card only changes
 * when the name, the role or the palette does. Same posture as `npm run icons`:
 * a generated asset, committed, regenerated by hand.
 *
 * Why a browser at all, when make-icons.mjs writes its PNG by hand: the icon is
 * two axis-aligned shapes and an arc, and this has type in it. Rasterising
 * Newsreader and JetBrains Mono from scratch would be several hundred lines of
 * glyph handling to avoid a binary that is already on every machine that can
 * run the dev server.
 *
 *   npm run og
 *
 * Set CHROME_PATH to override the search below.
 */
import { spawnSync } from 'node:child_process'
import { mkdtempSync, readdirSync, writeFileSync, existsSync, copyFileSync, rmSync } from 'node:fs'
import { tmpdir, homedir } from 'node:os'
import { join } from 'node:path'

/* The palette, kept in step with src/styles/theme.css by hand. The smoke suite
   checks that these values still appear there. */
const GROUND = '#14161d'
const SURFACE = '#1b1e27'
const INK = '#e8e6e0'
const DIM = '#8b939e'
const ACCENT = '#e8a33d'

const NAME = 'Rahim Mahat'
const ROLE = 'Senior Data Engineer'
const TAGLINE = 'a personal site you query instead of browse'
const HOST = 'rahim-stdin.pages.dev'

/** Every place a Chrome tends to be, most specific first. */
function findChrome() {
  if (process.env.CHROME_PATH) return process.env.CHROME_PATH

  // The headless shell hyperframes downloads, if this machine has ever rendered
  // the brag video. Versioned directory, so glob the one level.
  const hf = join(homedir(), '.cache', 'hyperframes', 'chrome', 'chrome-headless-shell')
  if (existsSync(hf)) {
    for (const v of readdirSync(hf)) {
      for (const inner of readdirSync(join(hf, v))) {
        for (const exe of ['chrome-headless-shell.exe', 'chrome-headless-shell']) {
          const p = join(hf, v, inner, exe)
          if (existsSync(p)) return p
        }
      }
    }
  }

  const candidates =
    process.platform === 'win32'
      ? [
          'C:/Program Files/Google/Chrome/Application/chrome.exe',
          'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
          join(homedir(), 'AppData/Local/Google/Chrome/Application/chrome.exe'),
          'C:/Program Files/Microsoft/Edge/Application/msedge.exe',
        ]
      : process.platform === 'darwin'
        ? [
            '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
            '/Applications/Chromium.app/Contents/MacOS/Chromium',
          ]
        : ['/usr/bin/google-chrome', '/usr/bin/chromium', '/usr/bin/chromium-browser']

  return candidates.find((p) => existsSync(p)) ?? null
}

const html = `<!doctype html>
<html><head><meta charset="utf-8">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&family=Newsreader:opsz,wght@6..72,300..500&display=swap">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  html, body { width: 1200px; height: 630px; overflow: hidden; }
  body {
    background: ${GROUND};
    color: ${INK};
    font-family: 'JetBrains Mono', ui-monospace, monospace;
    padding: 72px 80px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    background-image: radial-gradient(120% 90% at 50% 38%, rgba(232,163,61,.06) 0%, rgba(20,22,29,0) 58%, rgba(8,9,12,.5) 100%);
  }
  .ps1 { color: ${ACCENT}; }
  .prompt { font-size: 30px; line-height: 1.5; }
  .name { font-family: 'Newsreader', serif; font-weight: 400; font-size: 108px; line-height: 1.1; letter-spacing: -.015em; margin-top: 30px; }
  .role { font-size: 32px; line-height: 1.6; color: ${DIM}; margin-top: 16px; }
  .tag  { font-size: 28px; line-height: 1.6; color: ${DIM}; margin-top: 28px; }
  .foot { display: flex; align-items: center; justify-content: space-between; gap: 40px; white-space: nowrap; border-top: 1px solid ${SURFACE}; padding-top: 26px; }
  .mark { display: flex; align-items: center; gap: 16px; font-size: 30px; color: ${DIM}; }
  .blk  { display: block; width: 18px; height: 30px; background: ${ACCENT}; }
  .host { font-size: 28px; color: ${ACCENT}; }
</style></head>
<body>
  <div>
    <p class="prompt"><span class="ps1">rahim@stdin ~ %</span> whoami</p>
    <p class="name">${NAME}</p>
    <p class="role">${ROLE}</p>
    <p class="tag">${TAGLINE}</p>
  </div>
  <div class="foot">
    <span class="mark"><span class="blk"></span>stdin</span>
    <span class="host">${HOST}</span>
  </div>
</body></html>
`

const chrome = findChrome()
if (!chrome) {
  console.error(
    'make-og: no Chrome found. Set CHROME_PATH=/path/to/chrome and re-run.\n' +
      'public/og.png is committed, so this only matters when the card changes.',
  )
  process.exit(1)
}

const dir = mkdtempSync(join(tmpdir(), 'stdin-og-'))
const page = join(dir, 'card.html')
const shot = join(dir, 'screenshot.png')
writeFileSync(page, html)

const r = spawnSync(
  chrome,
  [
    '--headless',
    '--disable-gpu',
    '--hide-scrollbars',
    '--force-device-scale-factor=1',
    '--window-size=1200,630',
    // Fonts come off the network. Let the page settle before the shutter.
    '--virtual-time-budget=6000',
    `--screenshot=${shot}`,
    `file://${page.split('\\').join('/')}`,
  ],
  { stdio: 'inherit' },
)

if (r.status !== 0 || !existsSync(shot)) {
  console.error(`make-og: ${chrome} exited ${r.status} without writing a screenshot.`)
  rmSync(dir, { recursive: true, force: true })
  process.exit(1)
}

copyFileSync(shot, 'public/og.png')
rmSync(dir, { recursive: true, force: true })
console.log('wrote public/og.png (1200x630)')
